timestamp: 2022-02-06T17:12:53.286347
process title: pantsd [/Users/ekoaprilitrisno/liko/project/learn/python/learn-fastapi]
sys.argv: []
pid: 86029
Exception caught: (pants.engine.internals.scheduler.ExecutionError)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 234, in _run_inner
    return self._perform_run(goals)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 173, in _perform_run
    return self._perform_run_body(goals, poll=False)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 190, in _perform_run_body
    return self.graph_session.run_goal_rules(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/init/engine_initializer.py", line 135, in run_goal_rules
    exit_code = self.scheduler_session.run_goal_rule(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 533, in run_goal_rule
    self._raise_on_error([t for _, t in throws])
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 501, in _raise_on_error
    raise ExecutionError(

Exception message: 1 Exception encountered:

  ResolveError: The file or directory 'src/python/app/main' does not exist on disk in the workspace, so the address 'src/python/app/main:main' cannot be resolved.


timestamp: 2022-02-06T17:12:58.941083
process title: pantsd [/Users/ekoaprilitrisno/liko/project/learn/python/learn-fastapi]
sys.argv: []
pid: 86029
Exception caught: (pants.engine.internals.scheduler.ExecutionError)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 234, in _run_inner
    return self._perform_run(goals)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 173, in _perform_run
    return self._perform_run_body(goals, poll=False)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 190, in _perform_run_body
    return self.graph_session.run_goal_rules(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/init/engine_initializer.py", line 135, in run_goal_rules
    exit_code = self.scheduler_session.run_goal_rule(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 533, in run_goal_rule
    self._raise_on_error([t for _, t in throws])
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 501, in _raise_on_error
    raise ExecutionError(

Exception message: 1 Exception encountered:

  NoApplicableTargetsException: No applicable files or targets matched. The `run` goal works with these target types:

  * pex_binary

However, you only specified targets with these target types:

  * python_library

Please specify relevant files and/or targets. Run `./pants filter --target-type=pex_binary ::` to find all applicable targets in your project.


