17:12:53.28 [ERROR] Exception caught: (pants.engine.internals.scheduler.ExecutionError)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 234, in _run_inner
    return self._perform_run(goals)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 173, in _perform_run
    return self._perform_run_body(goals, poll=False)
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/bin/local_pants_runner.py", line 190, in _perform_run_body
    return self.graph_session.run_goal_rules(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/init/engine_initializer.py", line 135, in run_goal_rules
    exit_code = self.scheduler_session.run_goal_rule(
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 533, in run_goal_rule
    self._raise_on_error([t for _, t in throws])
  File "/Users/ekoaprilitrisno/.cache/pants/setup/bootstrap-Darwin-arm64/pants.nrMOpb/install/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 501, in _raise_on_error
    raise ExecutionError(

Exception message: 1 Exception encountered:

  ResolveError: The file or directory 'src/python/app/main' does not exist on disk in the workspace, so the address 'src/python/app/main:main' cannot be resolved.



(Use --print-stacktrace for more error details and/or --no-process-execution-local-cleanup to inspect chroots and/or -ldebug for more logs. See https://www.pantsbuild.org/v2.6/docs/troubleshooting for common issues. Consider reaching out for help: https://www.pantsbuild.org/v2.6/docs/getting-help.)
